"@echo off"  
"chcp 65001 >nul"  
"setlocal"  
"cd /d %~dp0"  
"set PORT=3000"  
"set SQLITE_PATH=one-api.db"  
"set SESSION_SECRET=change_this_to_random_string"  
"set DEBUG=false"  
"set TZ=Asia/Shanghai"  
"echo Starting One API on port %PORT% ..."  
"one-api.exe"  
"pause"  
"endlocal"  
